### ISSUE TITLE
Support option to prune empty directories during recursive delete

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/jfrog-cli-go#22]
I much prefer the CLI tool over using straight REST requests, on account of the support for wildcard paths. When I do something like this

`jfrog rt del --recursive=true repo1/*/path1/`

My intent would be to have the same result as having run

`curl -X DEL http://art.example.com/artifactory/repo1/.../path1`

for all existing `...` directories. Instead all the `repo1/*/path1/` folder structures are left in place, with only the files having been deleted. I think a `--prune` option would be good to combine with `--recursive=true`

**Comment by eyalbe4** [comment]
@jgeorgeson,
We started working on an improvement to the delete code that should provide the outcome you're looking for. We hope to add this to the next release.

**Comment by romangurevitch** [comment]
@jgeorgeson, 
We have released a new Jfrog cli version (1.5.1) which supports your request. 
It is enabled by default when deleting folder path with wildcard.
Thank you for your suggestion.

**Comment by jgeorgeson** [comment]
Thanks! It seems to be working but the output is a little confusing.

```
[jgeorgeson@woodhouse: /d01/sandboxes/jgeorgeson/workspaces/jfrog-cli]
$ jfrog rt s "test-deploy-snapshots/test/base1-sub3/*"
[Info:] Searching Artifactory using AQL query: items.find({"repo": "test-deploy-snapshots","$or": [{"$and": [{"path": {"$match":"test/base1-sub3"},"name":{"$match":"*"}}]},{"$and": [{"path": {"$match":"test/base1-sub3/*"},"name":{"$match":"*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size")
[Info:] Artifactory response: 200 OK
[Info:] Found 3 artifacts.
[
  {
    "path": "test-deploy-snapshots/test/base1-sub3/index.xml"
  },
  {
    "path": "test-deploy-snapshots/test/base1-sub3/plugins/plugin1.jar"
  },
  {
    "path": "test-deploy-snapshots/test/base1-sub3/plugins/plugin2.jar"
  }
]
[jgeorgeson@woodhouse: /d01/sandboxes/jgeorgeson/workspaces/jfrog-cli]
$ jfrog rt delete --dry-run "test-deploy-snapshots/test/base1-sub3/"
  test-deploy-snapshots/test/base1-sub3/
Are you sure you want to delete the above paths? (y/n): y
[Info:] [Dry run] Deleting: http://art.example.com/artifactory/test-deploy-snapshots/test/base1-sub3/
[jgeorgeson@woodhouse: /d01/sandboxes/jgeorgeson/workspaces/jfrog-cli]
$ jfrog rt delete "test-deploy-snapshots/test/base1-sub3/"
  test-deploy-snapshots/test/base1-sub3/
Are you sure you want to delete the above paths? (y/n): y
[Info:] Deleting: http://art.example.com/artifactory/test-deploy-snapshots/test/base1-sub3/
[Info:] Artifactory response: 204 No Content
[jgeorgeson@woodhouse: /d01/sandboxes/jgeorgeson/workspaces/jfrog-cli]
$ jfrog rt s "test-deploy-snapshots/test/base1-sub3/*"
[Info:] Searching Artifactory using AQL query: items.find({"repo": "test-deploy-snapshots","$or": [{"$and": [{"path": {"$match":"test/base1-sub3"},"name":{"$match":"*"}}]},{"$and": [{"path": {"$match":"test/base1-sub3/*"},"name":{"$match":"*"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size")
[Info:] Artifactory response: 200 OK
[Info:] Found 0 artifacts.
[]
```

Looking in the tree browser I can see the whole folder was deleted as desired, but the delete command output made me think nothing had been found (and thus not deleted).

**Comment by jgeorgeson** [comment]
I guess can close issue if you want since the functionality works.

**Comment by eyalbe4** [comment]
Thanks for the feedback @jgeorgeson. I guess you are referring to the "204 No content" response from Artifactory for the delete command (which is the valid response for a successful delete operation).
We will need to think how we can make the response less confusing, while keeping the behavior of prompting the response for all commands. Let's keep this issue open for now.

**Comment by dimatkach** [comment]
This is still not working for me on 1.5.1:
`jfrog rt del --recursive=true  'sandbox/*lookout-server-*'` returns 200 and says "Found 0 artifacts". 
`jfrog rt s --recursive=true  'sandbox/*lookout-server-*'`
finds nothing.

But in the GUI I can still see lots of empty folders looking like `sandbox/com/lookout/services/lookout-server-audit/1.0.DEV`

What gives?

**Comment by eyalbe4** [comment]
@dimatkach, the reason the empty directories were not removed is because in your scenario, no files had been found and therefore, nothing (including empty directories) was deleted. We would like to further improve the delete command, so that it handles this case as well.

**Comment by romangurevitch** [comment]
@dimatkach, we enhanced the CLI to support deleting empty folders.
This will be available with our next release of the CLI.

**Comment by yagee-de** [comment]
Thanks for c224bfd. Helped me to clean up our Artifactory OSS.

**Comment by eyalbe4** [comment]
@yagee-de and @jgeorgeson, version 1.7.0 is released and includes this functionality as part of the *delete* command. I'm therefore closing this issue.

**Comment by mazzy89** [comment]
@eyalbe4 I'm using the `del` command but unfortunately it doesn't clean the folder.  This is the AQL that I use:

```json
{
  "files": [
    {
      "aql": {
        "items.find": {
          "path": { "$match": "${repoPath}" }
        }
      }
    }
  ]
}
```
